import Head from "next/head";
import styles from "../styles/Home.module.css";
import Dashboard from "../components/Dashboard";
import Login from "../components/Login";
import {useEffect, useState} from "react";

export default function Home() {
  const [isAuthenticated, setIsAuthenticated] = useState(null);

  useEffect(() => {
    setIsAuthenticated(JSON.parse(localStorage.getItem('is_authenticated')));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS PWA App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <main className={styles.main}>
        {isAuthenticated ? (
          <Dashboard setIsAuthenticated={setIsAuthenticated} />
        ) : (
          <Login setIsAuthenticated={setIsAuthenticated} />
        )}
      </main>
    </div>
  );
}
